package pt.ist.fenixedu.integration.api;

import org.fenixedu.commons.i18n.LocalizedString;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Locale;

class ProfessionalCategoryOrder {

    //XXX Needed since this may differ from the intended use of the weight slot in TeacherCategory and ProfessionalCategory
    //XXX Also the mentioned slot is currently only used for teaching positions
    //XXX There are 2 categories exclusive to TeacherCategory (Colaborador Docente e Convidado)
    private static ArrayList<String> positionsByRelevance = new ArrayList<>();

    static {
        positionsByRelevance.add("Professor Catedrático");
        positionsByRelevance.add("Professor Catedrático Convidado");
        positionsByRelevance.add("Equiparado Professor Catedrático");
        positionsByRelevance.add("Professor Catedrático Visitante");
        positionsByRelevance.add("Professor Associado");
        positionsByRelevance.add("Professor Associado c/Agregação");
        positionsByRelevance.add("Professor Associado Convidado");
        positionsByRelevance.add("Equip.Prof.Associado Convidado");
        positionsByRelevance.add("Professor Associado Visitante");
        positionsByRelevance.add("Equiparado Professor Extraordinário");
        positionsByRelevance.add("Professor Auxiliar");
        positionsByRelevance.add("Prof Auxiliar C/Agregação");
        positionsByRelevance.add("Prof Auxiliar Convidado");
        positionsByRelevance.add("Equip. Prof. Auxiliar");
        positionsByRelevance.add("Equiparado Professor Auxiliar");
        positionsByRelevance.add("Equip.Prof.Auxiliar Convidado");
        positionsByRelevance.add("Assistente");
        positionsByRelevance.add("Assistente Convidado");
        positionsByRelevance.add("Equip. Assistente Convidado");
        positionsByRelevance.add("Assistente Estagiario");
        positionsByRelevance.add("Equip. Assistente");
        positionsByRelevance.add("Equiparado Assistente");
        positionsByRelevance.add("Equip.Assistente Estagiario");
        positionsByRelevance.add("Segundo Assistente");
        positionsByRelevance.add("Assistente Eventual");
        positionsByRelevance.add("Equiparado Assistente Eventual");
        positionsByRelevance.add("Monitor-E.C.D.U. c/Licenciatura");
        positionsByRelevance.add("Equip.Monitor C/Lic");
        positionsByRelevance.add("Monitor-E.C.D.U.s/Licenciatura");
        positionsByRelevance.add("Equip.Monitor S/Lic");
        positionsByRelevance.add("Educador Infância");
        positionsByRelevance.add("Monitor-E.C.D.U.");
        positionsByRelevance.add("Professor Adjunto");
        positionsByRelevance.add("Equip.Investigador Coordenador");
        positionsByRelevance.add("Equip.Investigador Principal");
        positionsByRelevance.add("Equip.Investigador Auxiliar");
        positionsByRelevance.add("Equip.Investigador Auxiliar Convidado");
        positionsByRelevance.add("Equip.Assistente de Investigaçao");
        positionsByRelevance.add("Equip.Estagiario Investigador");
        positionsByRelevance.add("Investigador Coordenador");
        positionsByRelevance.add("Investigador Principal Com Habilitacao");
        positionsByRelevance.add("Invest.Princip. c/Agregação");
        positionsByRelevance.add("Investigador Principal");
        positionsByRelevance.add("Investigador Coordenador Convidado");
        positionsByRelevance.add("Investigador Principal Convidado");
        positionsByRelevance.add("Investigador");
        positionsByRelevance.add("Técnico-Investigador");
        positionsByRelevance.add("Investigador Auxiliar");
        positionsByRelevance.add("Invest.Aux c/Agregação");
        positionsByRelevance.add("Investigador Auxiliar Convidado");
        positionsByRelevance.add("Assistente Investigação");
        positionsByRelevance.add("Estagiário Investigação");
        positionsByRelevance.add("Experienced Researcher");
        positionsByRelevance.add("Early Stage Researcher");
        positionsByRelevance.add("Doutorando Erasmus Mundus");
        positionsByRelevance.add("Mestrando Erasmus Mundus");
        positionsByRelevance.add("Nível de Consolidação (Advanced Grant)");
        positionsByRelevance.add("Nível de Desenvolvimento (Develop Grant)");
        positionsByRelevance.add("Nível Inicial (Starting Grant)");
        positionsByRelevance.add("Colaborador do IST-ID/IC");
        positionsByRelevance.add("Colaborador do IST-ID/IP");
        positionsByRelevance.add("Colaborador do IST-ID/IA");
        positionsByRelevance.add("Colaborador do IST-ID/AI");
        positionsByRelevance.add("Colaborador Não Remunerado Investigador");
        positionsByRelevance.add("Colaborador da ADIST/IP");
        positionsByRelevance.add("Colaborador da ADIST/IA");
        positionsByRelevance.add("Colaborador da ADIST/AI	");
        positionsByRelevance.add("Eq. Chefe Secção");
        positionsByRelevance.add("Eq. Assistente Administr. Especialista");
        positionsByRelevance.add("Eq. Assistente Administrativo Principal");
        positionsByRelevance.add("Eq. Assistente Administrativo");
        positionsByRelevance.add("Chefe Secção");
        positionsByRelevance.add("Chefe de Repartiçao");
        positionsByRelevance.add("Oficial Administrativo Principal");
        positionsByRelevance.add("Terceiro Oficial");
        positionsByRelevance.add("Assistente Administrativo Especialista");
        positionsByRelevance.add("Assistente Administrativo Principal");
        positionsByRelevance.add("Assistente Administrativo");
        positionsByRelevance.add("Eq. Auxiliar Tecnico");
        positionsByRelevance.add("Eq. Auxiliar Administrativo");
        positionsByRelevance.add("Eq. Auxiliar Manutencao");
        positionsByRelevance.add("Eq. Auxiliar Limpeza");
        positionsByRelevance.add("Encarregado Auxiliar Administrativo");
        positionsByRelevance.add("Auxiliar Administrativo");
        positionsByRelevance.add("Fiel");
        positionsByRelevance.add("Fiel Armazem(atipica)");
        positionsByRelevance.add("Motorista Pesados");
        positionsByRelevance.add("Continuo 2 Cl");
        positionsByRelevance.add("Motorista Transportes Colectivos");
        positionsByRelevance.add("Telefonista");
        positionsByRelevance.add("Auxiliar Tecnico");
        positionsByRelevance.add("Auxiliar Tecnico Bad");
        positionsByRelevance.add("Eq. Tecnico Especialista Principal");
        positionsByRelevance.add("Eq. Tecnico Principal");
        positionsByRelevance.add("Eq. Tecnico 1 Cl");
        positionsByRelevance.add("Eq. Tecnico 2 Cl");
        positionsByRelevance.add("Tecnico Especialista Principal");
        positionsByRelevance.add("Tecnico Especialista");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Técnico Principal");
        positionsByRelevance.add("Tecnico  1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico  1 Cl");
        positionsByRelevance.add("Tecnico  Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico Especialista Principal");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico Especialista Principal");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico  1 Cl");
        positionsByRelevance.add("Tecnico Especialista Principal");
        positionsByRelevance.add("Tecnico Especialista");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Técnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Estagiario");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico 2 Cl");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl.");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Tecnico Principal");
        positionsByRelevance.add("Tecnico 1 Cl");
        positionsByRelevance.add("Encarregado Trabalhos");
        positionsByRelevance.add("Eq. Tec. Profis. Especialista Principal");
        positionsByRelevance.add("Eq. Tecnico Profissional Especialista");
        positionsByRelevance.add("Eq. Tecnico Profissional Principal");
        positionsByRelevance.add("Eq. Tecnico Profissional 1Cl");
        positionsByRelevance.add("Eq. Tecnico Profissional 2Cl");
        positionsByRelevance.add("Coordenador");
        positionsByRelevance.add("Tecnico Profissional Especialista Princi");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1 Cl");
        positionsByRelevance.add("Tecnico Profissional 2 Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1 Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional 1 Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1 Cl");
        positionsByRelevance.add("Tecnico Profissional 2 Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Coordenador");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1 Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional Especialista Princ.");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("Tecnico Profissional Principal");
        positionsByRelevance.add("Tecnico Profissional 1Cl");
        positionsByRelevance.add("Tecnico Profissional Especialista");
        positionsByRelevance.add("T. Profissional Principal");
        positionsByRelevance.add("T. Profissional 1ª Classe");
        positionsByRelevance.add("T. Profissional 2ª Classe");
        positionsByRelevance.add("Eq. Assessor  Principal");
        positionsByRelevance.add("Eq. Assessor");
        positionsByRelevance.add("Eq. Tecnico Superior Principal");
        positionsByRelevance.add("Eq. Tecnico Superior 1 Cl");
        positionsByRelevance.add("Eq. Tecnico Superior 2 Cl");
        positionsByRelevance.add("Eq. Tecnico Superior Estagiario");
        positionsByRelevance.add("Eq. Técnico Superior");
        positionsByRelevance.add("Eq. Técnico Superior (Estag)");
        positionsByRelevance.add("Técnico Superior");
        positionsByRelevance.add("Técnico Superior (Estagiário)");
        positionsByRelevance.add("Assessor Principal");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1A Cl");
        positionsByRelevance.add("Tecnico Superior 2A Cl");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior  1 Cl");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1 Cl");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1A Classe");
        positionsByRelevance.add("Tecnico Superior 2A Classe");
        positionsByRelevance.add("Assessor Principal");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1 Cl");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior 2 Cl");
        positionsByRelevance.add("Assessor  Principal");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1 Cl");
        positionsByRelevance.add("Assessor  Principal");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecnico Superior  1 Cl");
        positionsByRelevance.add("Tecnico Superior  2 Cl");
        positionsByRelevance.add("Assessor  Principal");
        positionsByRelevance.add("Tecnico Superior 1 Cl");
        positionsByRelevance.add("Tecnico Superior 2 Cl");
        positionsByRelevance.add("Tecnico Superior Estagiario");
        positionsByRelevance.add("Assessor  Principal");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Técnico Superior Principal");
        positionsByRelevance.add("Técnico Superior 1 Cl");
        positionsByRelevance.add("Técnico Superior 2 Cl");
        positionsByRelevance.add("Técnico Superior Estagiário");
        positionsByRelevance.add("Tec Sup Principal");
        positionsByRelevance.add("Tec Sup 1 Cl");
        positionsByRelevance.add("Tec Sup 2 Cl");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior 2 A Classe");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior 2A Classe");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior 2A Classe");
        positionsByRelevance.add("Tecn. Superior Principal");
        positionsByRelevance.add("Tecnico Superior 1A Classe");
        positionsByRelevance.add("Tecnico Superior  2A Classe");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecnico Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior 2A Classe");
        positionsByRelevance.add("Assessor");
        positionsByRelevance.add("Tecn. Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Tecn. Superior Principal");
        positionsByRelevance.add("Tecn. Superior 1A Classe");
        positionsByRelevance.add("Assessor Principal");
        positionsByRelevance.add("Assessor Principal");
        positionsByRelevance.add("Eq. Operario (Qualificado)");
        positionsByRelevance.add("Operario Encarregado (Altamente Qualific");
        positionsByRelevance.add("Projeccionista Principal");
        positionsByRelevance.add("Canalizador Principal");
        positionsByRelevance.add("Carpinteiro Principal");
        positionsByRelevance.add("Montador Telecomunicacoes Principal");
        positionsByRelevance.add("Estucador Principal");
        positionsByRelevance.add("Impressor Artes Graficas Principal");
        positionsByRelevance.add("Fotocopista Principal");
        positionsByRelevance.add("Fotocopista");
        positionsByRelevance.add("Marceneiro Principal");
        positionsByRelevance.add("Mecanico Principal");
        positionsByRelevance.add("Mecanico");
        positionsByRelevance.add("Mecanico Electricista Principal");
        positionsByRelevance.add("Mecanico Instrumentos Precisao Principal");
        positionsByRelevance.add("Montador Electricista Principal");
        positionsByRelevance.add("Pedreiro Principal");
        positionsByRelevance.add("Pintor Principal");
        positionsByRelevance.add("Pintor");
        positionsByRelevance.add("Soldador Principal");
        positionsByRelevance.add("Serralheiro Civil Principal");
        positionsByRelevance.add("Montador Estruturas");
        positionsByRelevance.add("Operador de Central Principal");
        positionsByRelevance.add("Encarregado");
        positionsByRelevance.add("Eq. Técnico Informática Grau 1 Nível 3");
        positionsByRelevance.add("Eq. Técnico Informática Grau 1 Nível 1");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 3 Nível 2");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 2 Nível 2");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 2 Nível 1");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 1 Nível 3");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 1 Nível 2");
        positionsByRelevance.add("Eq. Especialista Inform. Grau 1 Nível 1");
        positionsByRelevance.add("Eq. Especialista Inform. Estagiário c/ L");
        positionsByRelevance.add("Técnico Informática Grau 3 Nível 2");
        positionsByRelevance.add("Técnico Informática Grau 3 Nível 1");
        positionsByRelevance.add("Técnico Informática Grau 2 Nível 2");
        positionsByRelevance.add("Técnico Informática Grau 2 Nível 1");
        positionsByRelevance.add("Técnico Informática Grau 1 Nível 3");
        positionsByRelevance.add("Técnico Informática Grau 1 Nível 2");
        positionsByRelevance.add("Técnico Informática Grau 1 Nível 1");
        positionsByRelevance.add("Técnico Informática-Adjunto Nivel 2");
        positionsByRelevance.add("Técnico Informática-Adjunto Nivel 3");
        positionsByRelevance.add("Especialista Informática Grau 2");
        positionsByRelevance.add("Especialista Informática Grau 3 Nível 2");
        positionsByRelevance.add("Especialista Informática Grau 3 Nível 1");
        positionsByRelevance.add("Especialista Informática Grau 2 Nível 2");
        positionsByRelevance.add("Especialista Informática Grau 2 Nível 1");
        positionsByRelevance.add("Especialista Informática Grau 1 Nível 3");
        positionsByRelevance.add("Especialista Informática Grau 1 Nível 2");
        positionsByRelevance.add("Especialista Informática Estagiário c/ L");
        positionsByRelevance.add("Especialista Informática Grau 1 Nível 1");
        positionsByRelevance.add("Assessor Informático Principal");
        positionsByRelevance.add("Vice Presidente");
        positionsByRelevance.add("Director de Serviços");
        positionsByRelevance.add("Chefe Divisão");
        positionsByRelevance.add("Director-Executivo");
        positionsByRelevance.add("Director-Executivo Adjunto");
        positionsByRelevance.add("Dir.Superior 1º Grau");
        positionsByRelevance.add("Dir.Intermédia 1º Grau");
        positionsByRelevance.add("Dir.Intermédia 2º Grau");
        positionsByRelevance.add("Dir.Intermédia 3º Grau");
        positionsByRelevance.add("Dir.Intermédia 4º Grau");
        positionsByRelevance.add("Dir.Intermédia 5º Grau");
        positionsByRelevance.add("Eq. Coordenador Técnico");
        positionsByRelevance.add("Eq. Assistente Técnico");
        positionsByRelevance.add("Coordenador Técnico");
        positionsByRelevance.add("Assistente Técnico");
        positionsByRelevance.add("Eq. Assistente Operacional");
        positionsByRelevance.add("Encarregado Operacional");
        positionsByRelevance.add("Assistente Operacional");
        positionsByRelevance.add("Tecnico Superior");
        positionsByRelevance.add("Colaborador do IST-ID");
        positionsByRelevance.add("Colaborador do IST-ID/TS");
        positionsByRelevance.add("Colaborador do IST-ID/AT");
        positionsByRelevance.add("Colaborador do IST-ID/AO");
        positionsByRelevance.add("Colaborador Não Remunerado Não Docente");
        positionsByRelevance.add("Colaborador da ADIST");
        positionsByRelevance.add("Colaborador da ADIST/TS");
        positionsByRelevance.add("Colaborador da ADIST/CT");
        positionsByRelevance.add("Colaborador da ADIST/AT");
        positionsByRelevance.add("Colaborador da ADIST/EO");
        positionsByRelevance.add("Colaborador da ADIST/AO");
        positionsByRelevance.add("Colaborador da ADIST/EI");
        positionsByRelevance.add("Colaborador da ADIST/TI");
        positionsByRelevance.add("Colaborador Docente");
        positionsByRelevance.add("Colaborador Não Remunerado Docente");
        positionsByRelevance.add("Convidado");
        positionsByRelevance.add("Bolsa de Integração na Investigação");
        positionsByRelevance.add("Bolsa de Iniciação à Investigação");
        positionsByRelevance.add("Bolsa Iniciação Investigação (Bacharel)");
        positionsByRelevance.add("Bolsa de Investigação para Licenciado");
        positionsByRelevance.add("Bolsa de Investigação para Mestre");
        positionsByRelevance.add("Bolsa de Investigação para Doutor");
        positionsByRelevance.add("Bolsa p/Gestão de Ciência e Tecnologia");
        positionsByRelevance.add("Bolsa p/Gestão Ciência Tecnol. (Licenc.)");
        positionsByRelevance.add("Bolsa p/Gestão Ciência Tecnol. (Mestre)");
        positionsByRelevance.add("Bolsa p/Gestão Ciência Tecnol. (Doutor)");
        positionsByRelevance.add("Bolsa de Investigação Científica");
        positionsByRelevance.add("Bolsa para Técnico de Investigação");
        positionsByRelevance.add("Bolsa Técnico Investigação (Licenc.)");
        positionsByRelevance.add("Bolsa Técnico Invest. (S/Grau Académ.)");
        positionsByRelevance.add("Bolsa Técnico Invest. (C/ Grau Académ.)");
        positionsByRelevance.add("Bolsa para Cientista Convidado");
        positionsByRelevance.add("Bolsa de Desenv. de Carreira Científica");
        positionsByRelevance.add("Bolsa de Investigação Apoio ao Ensino");
        positionsByRelevance.add("Bolsa Invest. Apoio Ensino - 2º Ciclo");
        positionsByRelevance.add("Bolsa Invest. Apoio Ensino - 3º Ciclo");
        positionsByRelevance.add("Bolsa de Apoio à Gestão");
        positionsByRelevance.add("Bolsa de Apoio à Gestão (Licenciado)");
        positionsByRelevance.add("Bolsa de Investigação FCT");
        positionsByRelevance.add("Bolsa de Pós-Doutoramento");
        positionsByRelevance.add("Bolsa de Doutoramento");
        positionsByRelevance.add("Bolsa de Mestrado");
        positionsByRelevance.add("Bolsa de Investigação PRAXIS");
        positionsByRelevance.add("Bolsa de Investigação IST");
        positionsByRelevance.add("Bolsa Técnico Investigação (CERN)");
        positionsByRelevance.add("Colaborador do IST-ID/BL");
        positionsByRelevance.add("Colaborador da ADIST/BL");
    }

    public static Comparator<LocalizedString> comparator =
            Comparator.comparing(cat -> positionsByRelevance.indexOf(cat.getContent(Locale.forLanguageTag("pt"))));

}
