language: java
jdk:
  - oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.m2
  
# TODO: Remove the Strict Quote Escaping Flag once ACDM-472 is resolved
script: mvn clean test -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false jspc:compile -B
